# Generated by Django 2.2.24 on 2021-08-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210311_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
