# Generated by Django 2.2.24 on 2021-08-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pin_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='stars',
            field=models.CharField(blank=True, default=0, max_length=32, null=True),
        ),
    ]
