# Generated by Django 2.2.24 on 2021-08-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210816_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='isLogo',
            field=models.BooleanField(default=False),
        ),
    ]
